#
# Configuration file for the experiment HLSQG Sentence 73k replication
#
# Paper:
# A Recurrent BERT-based Model for Question Generation, Ying-Hong Chan, Yao-Chung Fan
# https://www.aclweb.org/anthology/D19-5821/

# experiment name
exp_name:
    "M-BERT-hlsqg-p60k-causal-v17"

# expeiment Log level
loglevel:
    info

# model
model_name:
    "bert-base-multilingual-cased"
# -----------------------------
# DataProcessingArguments
# -----------------------------

txtds_cache_dir:
    ./cached_txtds

# -------------------------------
# TrainingArguments
# -------------------------------
output_dir:
    "/scratch/project_2001403/ilmariky/{exp_name}-out"

logging_dir:
    "./{exp_name}-log"

do_train:
    true

do_eval:
    true

evaluate_during_training:
    true

num_train_epochs:
    8

logging_steps:
    10000

save_steps:
    30000

eval_steps:
    10000

save_total_limit:
    50

per_device_train_batch_size:
    16

per_device_eval_batch_size:
    16

# ----------
# fp16
# ----------
fp16:
    false

fp16_opt_level:
    O2


# ---------------
# GenerationArgs
# ---------------
do_gen_eval:
    true
sample_gen_eval:
    true
per_device_gen_eval_batch_size:
    16
n_sample_gen_eval:
    2000
